/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unit.convertor.view;

/**
 *
 * @author Pesan
 */
public class Temperature extends javax.swing.JFrame {

    /**
     * Creates new form Temperature
     */
    public Temperature() {
        initComponents();
    }

    //To change body of generated methods, choose Tools | Templates.

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        inUnit = new javax.swing.JComboBox<>();
        outUnit = new javax.swing.JComboBox<>();
        output = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        convert = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");
        setLocation(new java.awt.Point(275, 200));
        setMaximizedBounds(new java.awt.Rectangle(275, 200, 275, 200));
        setMinimumSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Temperature");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, -1));

        inUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Input Unit", "Celsius", "Fahrenheit", "Kelvin" }));
        getContentPane().add(inUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 129, -1, -1));

        outUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Output Unit", "Celsius", "Fahrenheit", "Kelvin" }));
        getContentPane().add(outUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        output.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        output.setForeground(new java.awt.Color(255, 255, 255));
        output.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 127, 210, 30));
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 129, 120, -1));

        convert.setText("Convert");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });
        getContentPane().add(convert, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 223, 95, 35));

        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 340, 95, 35));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 234, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pesan\\Desktop\\Lectures\\Level I - Semester II\\CS 1001\\Project\\tem.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        // TODO add your handling code here:
        String sInput = input.getText();
        String sInUnit = inUnit.getSelectedItem().toString();
        String sOutUnit = outUnit.getSelectedItem().toString();
        
        if (sInput.equals("")){
            output.setText("Please Enter a Value to Convert");
        }
        else {
        
        if (sInUnit=="Celsius"){
            if (sOutUnit=="Celsius"){
                double c2c = Double.parseDouble(sInput);
                output.setText(Double.toString(c2c));
            }
            else if (sOutUnit=="Fahrenheit"){
                double c2f = (Double.parseDouble(sInput)*9/5+32);
                output.setText(Double.toString(c2f));
            }
            else if (sOutUnit=="Kelvin"){
                double c2k = (Double.parseDouble(sInput)+273.15);
                output.setText(Double.toString(c2k));
                
            }
            else {
                output.setText("Please Select an Output Unit");
            }
        }
        else if (sInUnit=="Fahrenheit"){
            if (sOutUnit=="Celsius"){
                double f2c = (Double.parseDouble(sInput)-32)*5/9;
                output.setText(Double.toString(f2c));
            }
            else if (sOutUnit=="Fahrenheit"){
                double f2f = Double.parseDouble(sInput);
                output.setText(Double.toString(f2f));
            }
            else if (sOutUnit=="Kelvin"){
                double f2k = (Double.parseDouble(sInput)-32)*5/9+273.15;
                output.setText(Double.toString(f2k));
            }
            else {
                output.setText("Please Select an Output Unit");
            }
        }
        else if (sInUnit=="Kelvin") {
            if (sOutUnit=="Celsius"){
                double k2c = Double.parseDouble(sInput)-273.15;
                output.setText(Double.toString(k2c));
            }
            else if (sOutUnit=="Fahrenheit"){
                double k2f = (Double.parseDouble(sInput)-273.15)*9/5+32;
                output.setText(Double.toString(k2f));
            }
            else if (sOutUnit=="Kelvin"){
                double k2k = Double.parseDouble(sInput);
                output.setText(Double.toString(k2k));
            }
            else {
                output.setText("Please Select an Output Unit");
            }
        }
        else{
            output.setText("Please Select an Input Unit");
        }
        }
          
    }//GEN-LAST:event_convertActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperature().setVisible(true);
            }
        });
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert;
    private javax.swing.JComboBox<String> inUnit;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton menu;
    private javax.swing.JComboBox<String> outUnit;
    private javax.swing.JLabel output;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}

