/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shipping_compeny;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RFSSSFH
 */
public class frm_supp extends javax.swing.JFrame {

    /**
     * Creates new form frm_supp
     * @throws java.sql.SQLException
     */
    public frm_supp() throws SQLException {
        initComponents();
        fill_supp_tbl();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supp_cont = new javax.swing.JTextField();
        supp_mail = new javax.swing.JTextField();
        supp_add = new javax.swing.JTextField();
        supp_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supp_tbl = new javax.swing.JTable();
        supp_upd = new javax.swing.JButton();
        supp_del = new javax.swing.JButton();
        supp_enter = new javax.swing.JButton();
        supp_back = new javax.swing.JButton();
        supp_id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frm_supp"); // NOI18N

        jLabel2.setText("Supplier Id");

        jLabel1.setText("Supplier Name");

        jLabel5.setText("Email Id");

        jLabel4.setText("Supplier number");

        jLabel3.setText("Supplier Address");

        supp_tbl.setBackground(new java.awt.Color(204, 255, 255));
        supp_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Id", " Name", "Address", "Mobile", "Email id"
            }
        ));
        supp_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supp_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supp_tbl);

        supp_upd.setLabel("Update");
        supp_upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_updActionPerformed(evt);
            }
        });

        supp_del.setLabel("Delete");
        supp_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_delActionPerformed(evt);
            }
        });

        supp_enter.setLabel("Add");
        supp_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_enterActionPerformed(evt);
            }
        });

        supp_back.setText("Back");
        supp_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_backActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Wide Latin", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 153));
        jLabel6.setText("Supplier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(supp_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(supp_cont, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(supp_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(supp_enter)
                            .addGap(18, 18, 18)
                            .addComponent(supp_del)
                            .addGap(18, 18, 18)
                            .addComponent(supp_upd)
                            .addGap(18, 18, 18)
                            .addComponent(supp_back)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supp_name, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(supp_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supp_name)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(supp_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(supp_cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(supp_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supp_back)
                            .addComponent(supp_upd)
                            .addComponent(supp_del)
                            .addComponent(supp_enter))))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        public void fill_supp_tbl() throws SQLException{
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/thasneema?useSSL=false","root","");
            Statement stm=con.createStatement();
            String thas="SELECT * FROM supplier";
            ResultSet res=stm.executeQuery(thas);
            
            
           DefaultTableModel model=(DefaultTableModel)supp_tbl.getModel();
            
            Object[] row;
            
            while(res.next()){
            
                row = new Object[5];
                
                row[0]=res.getString("S_Id");
                row[1]=res.getString("S_Name");
                row[2]=res.getString("S_Address");
                row[3]=res.getString("S_Mobile");
                row[4]=res.getString("S_Email");
                
                model.addRow(row);
                
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_cust.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }

    
    
    private void supp_updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_updActionPerformed
        // TODO add your handling code here:
        dbcon thasneema=new dbcon();
        try {
            thasneema.upd_staff_cust_sup("supplier",supp_id.getText(),supp_name.getText(),supp_add.getText(),supp_cont.getText(),supp_mail.getText(),"S_Id","S_Name", "S_Address","S_Mobile","S_Email");

            DefaultTableModel model1=(DefaultTableModel) supp_tbl.getModel();
            model1.setRowCount(0);
            fill_supp_tbl();
            clr();

        } catch (SQLException ex) {
            Logger.getLogger(frm_cust.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_supp_updActionPerformed

    private void supp_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_delActionPerformed

        dbcon del=new dbcon();
        try {
            del.del_staff_cust_sup("supplier","S_Id",supp_id.getText());

            DefaultTableModel model1=(DefaultTableModel) supp_tbl.getModel();
            model1.setRowCount(0);
            fill_supp_tbl();
            clr();

        } catch (SQLException ex) {
            Logger.getLogger(frm_cust.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_supp_delActionPerformed

    private void supp_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_enterActionPerformed

        dbcon thasneema=new dbcon();
        try {
            thasneema.add_staff_cust_sup("supplier",supp_name.getText(),supp_add.getText(),supp_cont.getText(),supp_mail.getText(),"S_Name", "S_Address","S_Mobile","S_Email");
            DefaultTableModel model1=(DefaultTableModel) supp_tbl.getModel();
            model1.setRowCount(0);
            fill_supp_tbl();
            clr();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Some errors are occured  "+ex);
        }
    }//GEN-LAST:event_supp_enterActionPerformed

    private void supp_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supp_tblMouseClicked
        // TODO add your handling code here:
                
        int rowIndex=supp_tbl.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)supp_tbl.getModel();
        supp_id.setText(model.getValueAt(rowIndex,0).toString());
        supp_name.setText(model.getValueAt(rowIndex,1).toString());
        supp_add.setText(model.getValueAt(rowIndex,2).toString());
        supp_cont.setText(model.getValueAt(rowIndex,3).toString());
        supp_mail.setText(model.getValueAt(rowIndex,4).toString());
        
    }//GEN-LAST:event_supp_tblMouseClicked

    private void supp_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_backActionPerformed
        // TODO add your handling code here:
        
        
        frm_home hm=new frm_home();
        hm.setVisible(true);
        
        this.dispose();
        
        
    }//GEN-LAST:event_supp_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_supp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_supp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_supp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_supp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_supp().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frm_supp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    public void clr(){
    
            supp_name.setText("");
            supp_add.setText("");
            supp_cont.setText("");
            supp_mail.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField supp_add;
    private javax.swing.JButton supp_back;
    private javax.swing.JTextField supp_cont;
    private javax.swing.JButton supp_del;
    private javax.swing.JButton supp_enter;
    private javax.swing.JLabel supp_id;
    private javax.swing.JTextField supp_mail;
    private javax.swing.JTextField supp_name;
    private javax.swing.JTable supp_tbl;
    private javax.swing.JButton supp_upd;
    // End of variables declaration//GEN-END:variables
}
