/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shipping_compeny;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RFSSSFH
 */
public class frm_cust extends javax.swing.JFrame {
    
    

    /**
     * Creates new form frm_cust
     * @throws java.sql.SQLException
     */
    public frm_cust() throws SQLException {
        initComponents();
        fill_cust_tbl();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cust_name = new javax.swing.JTextField();
        cust_add = new javax.swing.JTextField();
        cust_cont = new javax.swing.JTextField();
        cust_mail = new javax.swing.JTextField();
        cust_back = new javax.swing.JButton();
        cust_enter = new javax.swing.JButton();
        cust_del = new javax.swing.JButton();
        cust_upd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cust_tbl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cust_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer");
        setName("frm_cust"); // NOI18N

        jLabel1.setText("Customer Name");

        jLabel3.setText("Customer Address");

        jLabel4.setText("Contact number");

        jLabel5.setText("Email Id");

        cust_cont.setName(""); // NOI18N
        cust_cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_contActionPerformed(evt);
            }
        });

        cust_back.setText("Back");
        cust_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_backActionPerformed(evt);
            }
        });

        cust_enter.setLabel("Add");
        cust_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_enterActionPerformed(evt);
            }
        });

        cust_del.setLabel("Delete");
        cust_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_delActionPerformed(evt);
            }
        });

        cust_upd.setLabel("Update");
        cust_upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_updActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Customer");

        cust_tbl.setAutoCreateRowSorter(true);
        cust_tbl.setBackground(new java.awt.Color(204, 255, 255));
        cust_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Name", "Address", "Mobile number", "Email"
            }
        ));
        cust_tbl.setAutoscrolls(false);
        cust_tbl.setName(""); // NOI18N
        cust_tbl.setSelectionBackground(new java.awt.Color(0, 255, 255));
        cust_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cust_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cust_tbl);

        jLabel6.setText("Customer Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cust_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cust_name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cust_add, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cust_cont, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(cust_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cust_enter)
                        .addGap(18, 18, 18)
                        .addComponent(cust_del)
                        .addGap(18, 18, 18)
                        .addComponent(cust_upd)
                        .addGap(18, 18, 18)
                        .addComponent(cust_back)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cust_id, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cust_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cust_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cust_cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cust_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cust_back)
                            .addComponent(cust_upd)
                            .addComponent(cust_del)
                            .addComponent(cust_enter))
                        .addGap(118, 118, 118))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cust_contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_contActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_contActionPerformed

    private void cust_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_enterActionPerformed

        dbcon thasneema=new dbcon();
        try {
            thasneema.add_staff_cust_sup("customer",cust_name.getText(),cust_add.getText(),cust_cont.getText(),cust_mail.getText(),"C_Name", "C_Address","C_Mobile","C_Email");

            DefaultTableModel model1=(DefaultTableModel) cust_tbl.getModel();
            model1.setRowCount(0);
            fill_cust_tbl();
            clr();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Some errors are occured  "+ex);
        }
    }//GEN-LAST:event_cust_enterActionPerformed

    private void cust_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cust_tblMouseClicked
        
        int rowIndex=cust_tbl.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)cust_tbl.getModel();
        cust_id.setText(model.getValueAt(rowIndex,0).toString());
        cust_name.setText(model.getValueAt(rowIndex,1).toString());
        cust_add.setText(model.getValueAt(rowIndex,2).toString());
        cust_cont.setText(model.getValueAt(rowIndex,3).toString());
        cust_mail.setText(model.getValueAt(rowIndex,4).toString());
    }//GEN-LAST:event_cust_tblMouseClicked

    private void cust_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_delActionPerformed

        dbcon del=new dbcon();
        try {
            del.del_staff_cust_sup("customer","C_Id",cust_id.getText());
            
            DefaultTableModel model1=(DefaultTableModel) cust_tbl.getModel();
            model1.setRowCount(0);
            fill_cust_tbl();
            clr();
            
        } catch (SQLException ex) {
            Logger.getLogger(frm_cust.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cust_delActionPerformed

    private void cust_updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_updActionPerformed
        // TODO add your handling code here:
        dbcon thasneema=new dbcon();
        try {
            thasneema.upd_staff_cust_sup("customer",cust_id.getText(),cust_name.getText(),cust_add.getText(),cust_cont.getText(),cust_mail.getText(),"C_Id","C_Name", "C_Address","C_Mobile","C_Email");
           
            DefaultTableModel model1=(DefaultTableModel) cust_tbl.getModel();
            model1.setRowCount(0);
            fill_cust_tbl();
            clr();
            
        } catch (SQLException ex) {
            Logger.getLogger(frm_cust.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }//GEN-LAST:event_cust_updActionPerformed

    private void cust_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_backActionPerformed
        // TODO add your handling code here:
        
        
        frm_home hm=new frm_home();
        hm.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_cust_backActionPerformed

    public void fill_cust_tbl() throws SQLException{
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost/thasneema?useSSL=false","root","");
            Statement stm=con.createStatement();
            String thas="SELECT * FROM customer";
            ResultSet res=stm.executeQuery(thas);
            
            
           DefaultTableModel model=(DefaultTableModel)cust_tbl.getModel();
            
            Object[] row;
            
            while(res.next()){
            
                row = new Object[5];
                
                row[0]=res.getString("C_Id");
                row[1]=res.getString("C_Name");
                row[2]=res.getString("C_Address");
                row[3]=res.getString("C_Mobile");
                row[4]=res.getString("C_Email");
                
                model.addRow(row);
                
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_cust.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    
    public void clr(){
            cust_name.setText("");
            cust_add.setText("");
            cust_cont.setText("");
            cust_mail.setText("");
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cust_add;
    private javax.swing.JButton cust_back;
    private javax.swing.JTextField cust_cont;
    private javax.swing.JButton cust_del;
    private javax.swing.JButton cust_enter;
    private javax.swing.JLabel cust_id;
    private javax.swing.JTextField cust_mail;
    private javax.swing.JTextField cust_name;
    private javax.swing.JTable cust_tbl;
    private javax.swing.JButton cust_upd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
