/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shipping_compeny;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RFSSSFH
 */
public class frm_staff extends javax.swing.JFrame {

    /**
     * Creates new form frm_supp
     * @throws java.sql.SQLException
     */
    public frm_staff() throws SQLException {
        initComponents();
        fill_staff_tbl();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staff_cont = new javax.swing.JTextField();
        staff_mail = new javax.swing.JTextField();
        staff_add = new javax.swing.JTextField();
        staff_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        staff_tbl = new javax.swing.JTable();
        staff_upd = new javax.swing.JButton();
        staff_del = new javax.swing.JButton();
        staff_enter = new javax.swing.JButton();
        staff_back = new javax.swing.JButton();
        staff_id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frm_supp"); // NOI18N

        jLabel2.setText("Staff Id");

        jLabel1.setText("Staff Name");

        jLabel5.setText("Email Id");

        jLabel4.setText("Staff number");

        jLabel3.setText("Staff Address");

        staff_tbl.setBackground(new java.awt.Color(204, 255, 255));
        staff_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff Id", " Name", "Address", "Mobile", "Email id"
            }
        ));
        staff_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staff_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(staff_tbl);

        staff_upd.setLabel("Update");
        staff_upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_updActionPerformed(evt);
            }
        });

        staff_del.setLabel("Delete");
        staff_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_delActionPerformed(evt);
            }
        });

        staff_enter.setLabel("Add");
        staff_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_enterActionPerformed(evt);
            }
        });

        staff_back.setText("Back");
        staff_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_backActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Niagara Engraved", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Staff");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(staff_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(staff_cont, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(staff_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(staff_enter)
                            .addGap(18, 18, 18)
                            .addComponent(staff_del)
                            .addGap(18, 18, 18)
                            .addComponent(staff_upd)
                            .addGap(18, 18, 18)
                            .addComponent(staff_back)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staff_name, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(staff_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staff_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staff_name)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(staff_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(staff_cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(staff_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staff_back)
                            .addComponent(staff_upd)
                            .addComponent(staff_del)
                            .addComponent(staff_enter)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        public void fill_staff_tbl() throws SQLException{
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/thasneema?useSSL=false","root","");
            Statement stm=con.createStatement();
            String thas="SELECT * FROM staff";
            ResultSet res=stm.executeQuery(thas);
            
            
           DefaultTableModel model=(DefaultTableModel)staff_tbl.getModel();
            
            Object[] row;
            
            while(res.next()){
            
                row = new Object[5];
                
                row[0]=res.getString("Staff_Id");
                row[1]=res.getString("Staff_Name");
                row[2]=res.getString("Staff_Address");
                row[3]=res.getString("Staff_Mobile");
                row[4]=res.getString("Staff_Email");
                
                model.addRow(row);
                
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_cust.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }

    
    
    private void staff_updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_updActionPerformed
        // TODO add your handling code here:
        dbcon thasneema=new dbcon();
        try {
            thasneema.upd_staff_cust_sup("staff",staff_id.getText(),staff_name.getText(),staff_add.getText(),staff_cont.getText(),staff_mail.getText(),"Staff_Id","Staff_Name", "Staff_Address","Staff_Mobile","Staff_Email");

            DefaultTableModel model1=(DefaultTableModel) staff_tbl.getModel();
            model1.setRowCount(0);
            fill_staff_tbl();
            clr();

        } catch (SQLException ex) {
            Logger.getLogger(frm_cust.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_staff_updActionPerformed

    private void staff_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_delActionPerformed

        dbcon del=new dbcon();
        try {
            del.del_staff_cust_sup("staff","Staff_Id",staff_id.getText());

            DefaultTableModel model1=(DefaultTableModel) staff_tbl.getModel();
            model1.setRowCount(0);
            fill_staff_tbl();
            clr();

        } catch (SQLException ex) {
            Logger.getLogger(frm_cust.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_staff_delActionPerformed

    private void staff_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_enterActionPerformed

        dbcon thasneema=new dbcon();
        try {
            thasneema.add_staff_cust_sup("staff",staff_name.getText(),staff_add.getText(),staff_cont.getText(),staff_mail.getText(),"Staff_Name", "Staff_Address","Staff_Mobile","Staff_Email");
            DefaultTableModel model1=(DefaultTableModel) staff_tbl.getModel();
            model1.setRowCount(0);
            fill_staff_tbl();
            clr();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Some errors are occured  "+ex);
        }
    }//GEN-LAST:event_staff_enterActionPerformed

    private void staff_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_tblMouseClicked
        // TODO add your handling code here:
                
        int rowIndex=staff_tbl.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)staff_tbl.getModel();
        staff_id.setText(model.getValueAt(rowIndex,0).toString());
        staff_name.setText(model.getValueAt(rowIndex,1).toString());
        staff_add.setText(model.getValueAt(rowIndex,2).toString());
        staff_cont.setText(model.getValueAt(rowIndex,3).toString());
        staff_mail.setText(model.getValueAt(rowIndex,4).toString());
        
    }//GEN-LAST:event_staff_tblMouseClicked

    private void staff_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_backActionPerformed
        // TODO add your handling code here:
        
        frm_home hm=new frm_home();
        hm.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_staff_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_staff().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frm_staff.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    public void clr(){
    
            staff_name.setText("");
            staff_add.setText("");
            staff_cont.setText("");
            staff_mail.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField staff_add;
    private javax.swing.JButton staff_back;
    private javax.swing.JTextField staff_cont;
    private javax.swing.JButton staff_del;
    private javax.swing.JButton staff_enter;
    private javax.swing.JLabel staff_id;
    private javax.swing.JTextField staff_mail;
    private javax.swing.JTextField staff_name;
    private javax.swing.JTable staff_tbl;
    private javax.swing.JButton staff_upd;
    // End of variables declaration//GEN-END:variables
}
